language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.8"

addons:
  postgresql: "10.0"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"

env:
  global:
    - VERSION="14.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - MQT_DEP=PIP